<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_MUX" Id="{a133e9c4-d39f-46fb-b382-f88dd4608554}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_MUX
VAR_INPUT
	in1,in2:INT;
END_VAR
VAR_OUTPUT
	out:INT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[out:=in1*in2;]]></ST>
    </Implementation>
    <LineIds Name="FB_MUX">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>